import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "@next/font/google";

import { Box } from "@mui/material";

import Navbar from "../components/Navbar";
import Achievements from "../components/Achievements";

import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isMenuOpen, setMenuOpen] = useState(false);
  const [header, setHeader] = useState("headerColor");

  const closeMenu = () => setMenuOpen(false);
  const openMenu = () => setMenuOpen(true);

  const listenScrollEvent = (event) => {
    const bgColorChanged = 373;

    if (window.scrollY < bgColorChanged) {
      return setHeader("headerColor");
    } else if (window.scrollY > bgColorChanged) {
      return setHeader("headerColor2");
    }
  };

  useEffect(() => {
    window.addEventListener("scroll", listenScrollEvent);

    return () => window.removeEventListener("scroll", listenScrollEvent);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className={header}>
        <Navbar
          onMenuIconClick={openMenu}
          close={closeMenu}
          isOpen={isMenuOpen}
          // languageToggle={handelLanguageToggle}
          sx={{
            backdropFilter: "blur(8px)",
            // color: "black",
          }}
        />
      </Box>

      <main className={styles.main}>
        <div className={styles.grid}>
          <Link href="/portfolio" className={styles.card}>
            <h2 className={inter.className}>
              Портфолио <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              информация о моей профессиональной деятельности
            </p>
          </Link>

          <Link href="/articles" className={styles.card}>
            <h2 className={inter.className}>
              Мои статьи <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Статьи на различные юридические темы
            </p>
          </Link>

          <Link href="/questions" className={styles.card}>
            <h2 className={inter.className}>
              Вопросы <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Здесь можно увидеть ответы на часто задаваемые вопросы
            </p>
          </Link>

          <Link href="/contacts" className={styles.card}>
            <h2 className={inter.className}>
              Контакты <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Мои контакты
              <br /> и форма связи
            </p>
          </Link>
        </div>

        <Link href="/questions" className={styles.card}>
          <Box sx={{ width: "255px", margin: "auto" }}>
            <h2 className={inter.className} align="center">
              Достижения <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Здесь можно увидеть сертификаты и ссылки на публикации
            </p>
          </Box>
        </Link>
        <Achievements />
      </main>
    </>
  );
}
