import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Achievements from "../components/Achievements";
// import Fancybox from "../components/Fancybox";

import { Box } from "@mui/material";
import Navbar from "../components/Navbar";

import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isMenuOpen, setMenuOpen] = useState(false);
  const [header, setHeader] = useState("headerColor");

  const closeMenu = () => setMenuOpen(false);
  const openMenu = () => setMenuOpen(true);

  const listenScrollEvent = (event) => {
    const bgColorChanged = 373;

    if (window.scrollY < bgColorChanged) {
      return setHeader("headerColor");
    } else if (window.scrollY > bgColorChanged) {
      return setHeader("headerColor2");
    }
  };

  useEffect(() => {
    window.addEventListener("scroll", listenScrollEvent);

    return () => window.removeEventListener("scroll", listenScrollEvent);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className={header}>
        <Navbar
          onMenuIconClick={openMenu}
          close={closeMenu}
          isOpen={isMenuOpen}
          // languageToggle={handelLanguageToggle}
          sx={{
            backdropFilter: "blur(8px)",
            // color: "black",
          }}
        />
      </Box>

      <main className={styles.main}>
        <div className={styles.center}>portfolio</div>
        <Achievements />
        {/* <Fancybox options={{ dragToClose: false }}>
          <p>
            <a data-fancybox="gallery" href="https://lipsum.app/id/33/1024x768">
              <img alt="" src="https://lipsum.app/id/33/200x150" />
            </a>

            <a data-fancybox="gallery" href="https://lipsum.app/id/34/1024x768">
              <img alt="" src="https://lipsum.app/id/34/200x150" />
            </a>

            <a data-fancybox="gallery" href="https://lipsum.app/id/35/1024x768">
              <img alt="" src="https://lipsum.app/id/35/200x150" />
            </a>

            <a data-fancybox="gallery" href="https://lipsum.app/id/36/1024x768">
              <img alt="" src="https://lipsum.app/id/36/200x150" />
            </a>
          </p>
        </Fancybox> */}

        <div className={styles.grid}>ffff</div>
      </main>
    </>
  );
}
