import { Box } from "@mui/material";
import { Inter } from "@next/font/google";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import Navbar from "../components/Navbar";
import { Footer } from "../footer/Footer";
import { AccordionPortfolio } from "../sections/accordionSection/AccordionPortfolio";

const inter = Inter({ subsets: [ "latin" ] });

export default function Home()
{
  const { t } = useTranslation("common");
  const [ isMenuOpen, setMenuOpen ] = useState(false);
  const [ header, setHeader ] = useState("headerColor");

  const closeMenu = () => setMenuOpen(false);
  const openMenu = () => setMenuOpen(true);

  const listenScrollEvent = (event) =>
  {
    const bgColorChanged = 373;

    if (window.scrollY < bgColorChanged)
    {
      return setHeader("headerColor");
    } else if (window.scrollY > bgColorChanged)
    {
      return setHeader("headerColor2");
    }
  };

  useEffect(() =>
  {
    window.addEventListener("scroll", listenScrollEvent);

    return () => window.removeEventListener("scroll", listenScrollEvent);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className={header}>
        <Navbar
          onMenuIconClick={openMenu}
          close={closeMenu}
          isOpen={isMenuOpen}
          // languageToggle={handelLanguageToggle}
          sx={{
            backdropFilter: "blur(8px)",
            // color: "black",
          }}
        />
      </Box>

      <Box component='main'
        className='main'
        sx={{ paddingBottom: '0px !important' }}
      >
        <h2 className={inter.className} align="center">
          {/* Статьи  */}
          {/* {t("welcome")} */}
          {t("portfolio")}
        </h2>

        <AccordionPortfolio />

        <Footer sx={{
          backgroundColor: "rgba(0, 179, 152, 1)",
          marginLeft: '-6rem',
          marginRight: '-6rem',
          width: 'calc(100% + 12rem)'
        }} />
        {/* <TopArrow /> */}

      </Box>
    </>
  );
}
export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, [ "common" ])),
  },
});
